# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Application.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QPixmap
import sys


class Ui_Frame(object):
    def setupUi(self, Frame):

        Frame.setObjectName("Frame")
        Frame.resize(637, 563)
        Frame.styleSheet()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Desktop/Books/alias-logo-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame.setWindowIcon(icon)
        Frame.setWindowOpacity(0.0)
        Frame.setToolTipDuration(-1)
        self.play = QtWidgets.QPushButton(Frame)
        self.play.setGeometry(QtCore.QRect(210, 110, 231, 71))
        self.play.setObjectName("play")
        self.rules = QtWidgets.QPushButton(Frame)
        self.rules.setGeometry(QtCore.QRect(210, 230, 231, 71))
        self.rules.setObjectName("rules")
        self.add_words = QtWidgets.QPushButton(Frame)
        self.add_words.setGeometry(QtCore.QRect(210, 350, 231, 71))
        self.add_words.setObjectName("add_words")
        self.label = QtWidgets.QLabel(Frame)
        self.lineEntry = QLineEdit(Frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 611, 531))
        self.label.setObjectName("label")
        self.label.setScaledContents(True)
        self.rules.raise_()
        self.play.raise_()
        self.add_words.raise_()
        self.label.raise_()
        self.back = QtWidgets.QPushButton(Frame)
        self.back.setGeometry(QtCore.QRect(10, 10, 100, 50))
        self.back.setObjectName("back")
        self.back.hide()
        my_qframe = Frame
        my_qframe.setStyleSheet(".QFrame { background-color:purple; }")
        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        self.lineEntry.move(170, 250)
        self.lineEntry.resize(300, 40)
        self.lineEntry.hide()
        self.add_button = QtWidgets.QPushButton(Frame)
        self.add_button.setGeometry(QtCore.QRect(280, 300, 80, 40))
        self.add_button.setObjectName("add_button")
        self.add_button.hide()

    def back_to_main(self):
        self.rules.show()
        self.play.show()
        self.add_words.show()
        self.back.hide()
        self.label.hide()
        self.lineEntry.hide()
        self.add_button.hide()

    def changelabeltext(self):
        # changing the text of label after button get clicked
        # Hiding pushbutton from the main window
        # after button get clicked.
        self.rules.hide()
        self.play.hide()
        self.add_words.hide()
        self.back.show()

        pixmap = QPixmap('rules.png')
        self.label.setPixmap(pixmap)
        self.label.show()

    def words(self):

        self.rules.hide()
        self.play.hide()
        self.add_words.hide()
        self.back.show()
        self.lineEntry.show()
        self.add_button.show()


    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Alias"))
        self.play.setText(_translate("Frame", "Play"))
        self.rules.setText(_translate("Frame", "Rules"))
        self.add_words.setText(_translate("Frame", "Add words"))
        self.back.setText(_translate("Frame", "Back"))
        self.label.setText(_translate("Frame", "Rules"))
        self.rules.clicked.connect(self.changelabeltext)
        self.back.clicked.connect(self.back_to_main)
        self.add_words.clicked.connect(self.words)
        self.label.hide()
        self.label.setGeometry(QtCore.QRect(20, 70, 600, 450))
        # keeping the text of label empty before button get clicked
        self.label.setText("")

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
