from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSignalTransition
import PyQt5
from PyQt5.QtWidgets import QApplication, QLabel, QLineEdit, QVBoxLayout, QWidget
from third_windows import Ui_MainWindow


class Ui_choose_window(object):
    def open_third_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.ui.lcdNumber.setProperty("value", self.time.text())
        self.ui.teams = [self.team1_name.text(), self.team2_name.text(), self.team3_name.text(), self.team4_name.text(), self.team5_name.text(),
                         self.team6_name.text()]
        thing = self.points.text()
        self.ui.points.setText(thing)
        self.window.show()
        self.ui.Start()

    def setupUi(self, choose_window):
        choose_window.setObjectName("choose_window")
        choose_window.resize(490, 417)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        choose_window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(choose_window)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_options = QtWidgets.QLabel(self.centralwidget)
        self.choose_options.setGeometry(QtCore.QRect(160, 10, 161, 20))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(12)
        font.setItalic(True)
        self.choose_options.setFont(font)
        self.choose_options.setObjectName("choose_options")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 131, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groups = QtWidgets.QLineEdit(self.centralwidget)
        self.groups.setGeometry(QtCore.QRect(150, 50, 41, 21))
        self.groups.setObjectName("groups")
        self.points = QtWidgets.QLineEdit(self.centralwidget)
        self.points.setGeometry(QtCore.QRect(300, 50, 41, 21))
        self.points.setObjectName("points")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 50, 91, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 50, 91, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.time = QtWidgets.QLineEdit(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(440, 50, 41, 21))
        self.time.setObjectName("time")
        self.play_game = QtWidgets.QPushButton(self.centralwidget)
        self.play_game.setGeometry(QtCore.QRect(200, 310, 95, 36))
        self.play_game.setObjectName("play_game")
        self.team1 = QtWidgets.QLabel(self.centralwidget)
        self.team1.setGeometry(QtCore.QRect(50, 100, 61, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.team1.setFont(font)
        self.team1.setObjectName("team1")
        self.team1_name = QtWidgets.QLineEdit(self.centralwidget)
        self.team1_name.setGeometry(QtCore.QRect(50, 120, 141, 21))
        self.team1_name.setObjectName("team1_name")
        self.team2_name = QtWidgets.QLineEdit(self.centralwidget)
        self.team2_name.setGeometry(QtCore.QRect(260, 120, 141, 21))
        self.team2_name.setObjectName("team2_name")
        self.team2 = QtWidgets.QLabel(self.centralwidget)
        self.team2.setGeometry(QtCore.QRect(260, 100, 61, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.team2.setFont(font)
        self.team2.setObjectName("team2")
        self.team4_name = QtWidgets.QLineEdit(self.centralwidget)
        self.team4_name.setGeometry(QtCore.QRect(260, 190, 141, 21))
        self.team4_name.setObjectName("team4_name")
        self.team3_name = QtWidgets.QLineEdit(self.centralwidget)
        self.team3_name.setGeometry(QtCore.QRect(50, 190, 141, 21))
        self.team3_name.setObjectName("team3_name")
        self.team4 = QtWidgets.QLabel(self.centralwidget)
        self.team4.setGeometry(QtCore.QRect(260, 170, 61, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.team4.setFont(font)
        self.team4.setObjectName("team4")
        self.team3 = QtWidgets.QLabel(self.centralwidget)
        self.team3.setGeometry(QtCore.QRect(50, 170, 61, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.team3.setFont(font)
        self.team3.setObjectName("team3")
        self.team6_name = QtWidgets.QLineEdit(self.centralwidget)
        self.team6_name.setGeometry(QtCore.QRect(260, 250, 141, 21))
        self.team6_name.setObjectName("team6_name")
        self.team6 = QtWidgets.QLabel(self.centralwidget)
        self.team6.setGeometry(QtCore.QRect(260, 230, 61, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.team6.setFont(font)
        self.team6.setObjectName("team6")
        self.team5 = QtWidgets.QLabel(self.centralwidget)
        self.team5.setGeometry(QtCore.QRect(50, 230, 61, 17))
        font = QtGui.QFont()
        font.setFamily("GHEA Grapalat")
        font.setPointSize(10)
        self.team5.setFont(font)
        self.team5.setObjectName("team5")
        self.team5_name = QtWidgets.QLineEdit(self.centralwidget)
        self.team5_name.setGeometry(QtCore.QRect(50, 250, 141, 21))
        self.team5_name.setObjectName("team5_name")
        choose_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(choose_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 30))
        self.menubar.setObjectName("menubar")
        choose_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(choose_window)
        self.statusbar.setObjectName("statusbar")
        choose_window.setStatusBar(self.statusbar)
        self.all_labels = [self.team1, self.team2, self.team3, self.team4, self.team5, self.team6]
        self.all_groups = [self.team1_name, self.team2_name, self.team3_name, self.team4_name, self.team5_name,
                           self.team6_name]
        for i in range(6):
            self.all_groups[i].hide()
            self.all_labels[i].hide()

        self.retranslateUi(choose_window)
        QtCore.QMetaObject.connectSlotsByName(choose_window)

    def add_groups(self):

        if self.groups.text() != "":
            number_of_teams = int(self.groups.text())
        else:
            number_of_teams = 6
        if self.groups.text() != "":
            for i in range(number_of_teams):
                self.all_groups[i].show()
                self.all_labels[i].show()
        else:
            for i in range(number_of_teams):
                self.all_groups[i].hide()
                self.all_labels[i].hide()

    def retranslateUi(self, choose_window):
        _translate = QtCore.QCoreApplication.translate
        choose_window.setWindowTitle(_translate("choose_window", "Alias"))
        self.choose_options.setText(_translate("choose_window", "Choose the options"))
        self.label.setText(_translate("choose_window", "The number of groups"))
        self.label_2.setText(_translate("choose_window", "Points to win"))
        self.label_3.setText(_translate("choose_window", "Round time"))
        self.play_game.setText(_translate("choose_window", "Play"))
        self.team1.setText(_translate("choose_window", "Team 1"))
        self.team2.setText(_translate("choose_window", "Team 2"))
        self.team4.setText(_translate("choose_window", "Team 4"))
        self.team3.setText(_translate("choose_window", "Team 3"))
        self.team6.setText(_translate("choose_window", "Team 6"))
        self.team5.setText(_translate("choose_window", "Team 5"))
        self.groups.textChanged.connect(self.add_groups)
        self.play_game.clicked.connect(self.open_third_window)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QMainWindow()
    ui = Ui_choose_window()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
